USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/sharp/303sh/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := unknown
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := krait
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := 303sh

BOARD_KERNEL_CMDLINE := androidboot.hardware=qcom user_debug=31 maxcpus=2 msm_rtb.filter=0x3F ehci-hcd.park=3
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 2048
TARGET_KERNEL_SOURCE := kernel/sharp/303sh
TARGET_KERNEL_CONFIG := defconfig_sharp_303sh

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x84072580
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x84072580
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2117074944
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_FLASH_BLOCK_SIZE := 131072
TARGET_USERIMAGES_USE_EXT4=true

BOARD_HAS_NO_SELECT_BUTTON := true

#TWRP config
#DEVICE_RESOLUTION := 1080x1920
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TW_NO_REBOOT_BOOTLOADER := true
TW_EXTERNAL_STORAGE_PATH := "/external_sd"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "sdcard"
BOARD_HAS_NO_REAL_SDCARD := true
#TW_TARGET_USES_QCOM_BSP := true
TW_THEME :=  portrait_hdpi
RECOVERY_SDCARD_ON_DATA := true
TW_INCLUDE_CRYPTO := false
TW_EXCLUDE_MTP := true
TWHAVE_SELINUX := true
TW_DEFAULT_BRIGHTNESS := 150
TW_CUSTOM_BATTERY_PATH := /sys/class/power_supply/battery/capacity
TWRP_INCLUDE_LOGCAT := true
TW_EXTRA_LANGUAGES := true 
TW_DEFAULT_LANGUAGE := zh_CN
BOARD_RECOVERY_SWIPE := true
TARGET_NO_SEPARATE_RECOVERY := true

TARGET_RECOVERY_FSTAB := device/sharp/303sh/recovery.fstab

TW_EXCLUDE_SUPERSU := true

